### ISSUE TITLE
AccontController is not being used anyhow?

### ISSUE THREAD

**Issue by apryiomka** [DuckMan435/PortfolioViewer#3]
It is not an issue, i guess, it just was not implemented to handle membership?

**Comment by DuckMan435** [comment]
I was planning on using the AccountController to handle membership via an "Admin" user to create users, but was having issues so I created the users / roles via a Seed method.  I chose to focus on the primary tasks and circle back if I had time.

**Comment by apryiomka** [comment]
This is what i though, I was just curious since it was there :)
