### ISSUE TITLE
No unit tests?

### ISSUE THREAD

**Issue by apryiomka** [DuckMan435/PortfolioViewer#5]
I wonder if you would come up with a handful of test cases for the app (controllers, etc)?

**Comment by DuckMan435** [comment]
I would most likely make unit tests revolving around the retrieval / building of portfolios and their associated securities.  Some tests such as if the security within the portfolio I pulled was a "Stock", that it has all the appropriate info that is associated with defining a security as a "Stock".  Same goes for the other two security types.

**Comment by apryiomka** [comment]
Would you write a couple of unit tests to demonstrate this?

**Comment by DuckMan435** [comment]
Unit Tests now added.

**Comment by apryiomka** [comment]
Thanks for adding the tests project, looks great!
